# site settings
title: Forty
subtitle: by HTML5 UP
email: coreyclip@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: coreyclip.github.io # the base hostname & protocol for your site
author:
street_address: 
city: Taipei
state: 
zip_code: 
country: Taiwan 
phone: +1 (949) 949-529-428 (US) 0909 364 503 (TW)  

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/coreyclip
  GitLab:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/corey-c-8033b825/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
